services:
  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
  
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

volumes:
  mongo-data:
      